name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Build plugin
        run: |
          npm ci
          npm run build

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          
          # 创建发布版本 - 只包含Obsidian插件所需的三个关键文件
          gh release create "$tag" \
            --title "版本 $tag" \
            --notes "此版本包含Obsidian插件所需的三个核心文件：main.js、manifest.json和styles.css。" \
            main.js manifest.json styles.css